export const BRANDS_DIRECTORY = [
  {"url": "https://www.cimalp.fr/", "name": "Cimalp", "domain": "cimalp.fr"},
  {"url": "https://eu.patagonia.com/fr/fr/home/", "name": "Patagonia", "domain": "patagonia.com"},
  {"url": "https://www.thenorthface.com/fr-fr", "name": "The North Face", "domain": "thenorthface.com"},
  {"url": "https://www.millet.com/fr_fr/", "name": "Millet", "domain": "millet.com"},
  {"url": "https://www.salomon.com/fr-fr", "name": "Salomon", "domain": "salomon.com"},
  {"url": "https://www.mammut.com/fr/fr", "name": "Mammut", "domain": "mammut.com"},
  {"url": "https://rab.equipment/eu-fr/", "name": "Rab", "domain": "rab.equipment"},
  {"url": "https://www.samaya-equipment.com/", "name": "Samaya", "domain": "samaya-equipment.com"},
  {"url": "https://durstongear.com/", "name": "Durston", "domain": "durstongear.com"},
  {"url": "https://cascadedesigns.com/fr-eu/pages/msr?view=sl-EAD72041", "name": "MSR", "domain": "cascadedesigns.com"},
  {"url": "https://cascadedesigns.com/fr-eu/pages/thermarest", "name": "Therm-a-Rest", "domain": "cascadedesigns.com"},
  {"url": "https://www.osprey.com/fr/", "name": "Osprey", "domain": "osprey.com"},
  {"url": "https://www.toaksoutdoor.com/", "name": "TOAKS", "domain": "toaksoutdoor.com"},
  {"url": "https://okoeurope.com/", "name": "ÖKO Europe", "domain": "okoeurope.com"},
  {"url": "https://www.hydrapak.fr/fr/", "name": "Hydrapak", "domain": "hydrapak.com"},
  {"url": "https://www.nitecore-france.com/", "name": "Nitecore", "domain": "nitecore.com"},
  {"url": "https://eu.blackdiamondequipment.com/fr", "name": "Black Diamond", "domain": "blackdiamondequipment.com"},
  {"url": "https://seatosummit.eu/fr-fr", "name": "Sea to Summit", "domain": "seatosummit.com"},
  {"url": "https://nalgene.eu/fr/", "name": "Nalgene", "domain": "nalgene.com"},
  {"url": "https://www.nemoequipment.com/", "name": "NEMO", "domain": "nemoequipment.com"},
  {"url": "https://www.katadyngroup.com/fr/fr", "name": "Katadyn", "domain": "katadyngroup.com"},
  {"url": "https://www.petzl.com/FR/fr", "name": "Petzl", "domain": "petzl.com"},
  {"url": "https://www.oakley.com/fr-fr", "name": "Oakley", "domain": "oakley.com"},
  {"url": "https://zpacks.com/", "name": "Zpacks", "domain": "zpacks.com"},
  {"url": "https://cumulus.equipment/fr/eu", "name": "Cumulus", "domain": "cumulus.equipment"},
  {"url": "https://hyperlitemountaingear.com/", "name": "Hyperlite", "domain": "hyperlitemountaingear.com"},
  {"url": "https://www.garmin.com/fr-FR/", "name": "Garmin", "domain": "garmin.com"},
  {"url": "https://fr.coros.com/", "name": "COROS", "domain": "coros.com"},
  {"url": "https://www.jetboil.fr/fr/", "name": "Jetboil", "domain": "jetboil.com"},
  {"url": "https://montane.com/", "name": "Montane", "domain": "montane.com"},
  {"url": "https://www.simond.com/fr-FR", "name": "Simond", "domain": "simond.com"},
  {"url": "https://www.naturehike.com/fr-fr", "name": "Naturehike", "domain": "naturehike.com"},
  {"url": "https://helinox.eu/fr", "name": "Helinox", "domain": "helinox.com"},
  {"url": "https://www.columbiasportswear.fr/", "name": "Columbia", "domain": "columbiasportswear.fr"},
  {"url": "https://arcteryx.com/fr/fr", "name": "Arc'teryx", "domain": "arcteryx.com"},
  {"url": "https://www.decathlon.fr/", "name": "Decathlon", "domain": "decathlon.fr"},
  {"url": "https://www.flextail.com/fr-fr", "name": "FLEXTAIL", "domain": "flextail.com"},
  {"url": "https://raidlight.com/", "name": "Raidlight", "domain": "raidlight.com"},
  {"url": "https://eu.gregorypacks.com/fr-fr/home/", "name": "Gregory", "domain": "gregorypacks.com"},
  {"url": "https://www.julbo.com/fr_fr", "name": "Julbo", "domain": "julbo.com"},
  {"url": "https://www.lasportiva.com/fr", "name": "La Sportiva", "domain": "lasportiva.com"},
  {"url": "https://primusequipment.com/en-eu", "name": "Primus", "domain": "primusequipment.com"},
  {"url": "https://eu-main.iniushop.com/fr", "name": "INIU", "domain": "iniushop.com"},
  {"url": "https://www.dji.com/fr", "name": "DJI", "domain": "dji.com"},
  {"url": "https://www.lyophilise.fr/", "name": "Lyophilisé.fr", "domain": "lyophilise.fr"}
].sort((a, b) => a.name.localeCompare(b.name));
